---
title: "Lecture6b_Markdown"
author: "Amanda"
date: "3/3/2021"
output: 
  html_document:
    toc: TRUE
    toc_float: TRUE
    theme: journal
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      message=FALSE, 
                      warning=FALSE, 
                      fig.path="../Output/")
```

# Introduction 
Today, we will use **Palmer Penguins** to manipulate figures in RMarkdown.

# Load Libraries
```{r, message=FALSE, warning=FALSE}
library(palmerpenguins)
library(tidyverse)
library(here)
library(kableExtra)
```

# Make a plot
```{r PengFig, fig.align="center", fig.cap="This is a figure of penguin flippers.", echo=FALSE}
PenguinFigure<- penguins%>%
  ggplot(aes(x = species, y = flipper_length_mm, color = island))+
  geom_boxplot()

PenguinFigure
```

# Make a table (without previous data)

| table 1 | col 2|
|:--------|:----:|
|1        |2     |

I use a col to decide alignment.

| Time  | Session | Topic    |
|:------|:-------:|---------:|
| _left_ | _center_| _right_ |
| 01:00  | 1       | Anatomy |
| 01:50  |         | *Break* |
| 02:00  | 2       | Tables  |
| 02:45  |         | *Break* |

# Make a data with penguin data 
```{r}
penguins%>%
  group_by(species) %>%
  summarise(billmean = mean(bill_length_mm, na.rm = TRUE))%>%
  kbl() %>% # this creates a formatted table
  kable_classic() %>% 
  row_spec(2, bold = TRUE, color = "white", background = "grey") 
```

